apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-pull-secrets-test
spec:
  template:
    metadata:
      labels:
        app: image-pull-secrets-test
    spec:
      imagePullSecrets:
      - name: image-pull-secrets
      containers:
      - name: echo
        image: rknt/worktimer-sync:20260627150950-068f610
        ports:
        - name: http
          containerPort: 5678
          protocol: TCP
        args:
        - --status-code=401
        resources:
          limits:
            cpu: 10m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
  selector:
    matchLabels:
      app: image-pull-secrets-test
