apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-pull-secrets
  namespace: kyverno
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: image-pull-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: clusters/${cluster_name}/image-pull-secrets
